#!/usr/bin/env python3

import sys
from pathlib import Path
import subprocess

def main():
    if len(sys.argv) != 3:
        print("Usage: ./assembly input_reads.fasta output_contigs.fasta")
        sys.exit(1)

    input_fasta = sys.argv[1]
    output_fasta = Path(sys.argv[2])

    outdir = Path("assembly_tmp")
    outdir.mkdir(exist_ok=True)

    # wywołujemy PRAWDZIWY main
    cmd = [
        sys.executable,
        str(Path(__file__).parent / "src" / "run_assembly.py"),
        "-I", input_fasta,
        "-O", str(outdir)
    ]

    subprocess.run(cmd, check=True)

    contigs = outdir / "contigs.fasta"
    if not contigs.exists():
        print("ERROR: contigs.fasta not produced")
        sys.exit(1)

    output_fasta.parent.mkdir(parents=True, exist_ok=True)
    contigs.replace(output_fasta)

if __name__ == "__main__":
    main()
